// HexGrid module barrel.
export {
  HexGrid,
  type HexGridOptions,
  type WorkloadInput,
  type HexResourceInput,
  type WorkloadSummary,
  type ResourceLink,
  type LinkStyle,
} from './hexgrid-viz';
export {
  axialToPixel,
  pixelToAxial,
  hexRound,
  hexNeighbors,
  hexDistance,
  hexRing,
  hexSpiral,
  spiralCount,
  spiralRadiusFor,
  hexPolygon,
  axialKey,
  type Axial,
} from './hex';
export {
  HexPlacer,
  placeHierarchical,
  placeRelational,
  placementKey,
  serializePlacement,
  restorePlacement,
  hashString,
  PLACEMENT_VERSION,
  type PlacedWorkload,
  type GroupedItem,
  type HierItem,
  type RelItem,
  type RelationalOptions,
  type PlacementSnapshot,
} from './placement';
