// Color module barrel — palettes and scale functions.
export {
  SEQUENTIAL,
  DIVERGING,
  CATEGORICAL,
  SEQUENTIAL_NAMES,
  DIVERGING_NAMES,
  CATEGORICAL_NAMES,
  isSequential,
  isDiverging,
  isCategorical,
  type SequentialName,
  type DivergingName,
  type CategoricalName,
  type PaletteName,
} from './palettes';
export {
  hexToRgba,
  interpolateRgb,
  oklchToRgba,
  rgbaToOklch,
  resolveColor,
  sampleStops,
  sequential,
  diverging,
  categorical,
  paletteStops,
  type ColorInput,
  type ColorScale,
} from './scales';
export {
  SURFACE,
  INK,
  STATUS,
  BACKGROUND,
  NEUTRAL,
  NEUTRAL_LIGHT,
  HAIRLINE,
  HOT,
  GLYPH_DARK,
  GLYPH_LIGHT,
} from './tokens';
